#!/usr/bin/env sh
set -eu
# Don't ignore any of these checks
pnpm run format
pnpm exec lint-staged
pnpm run type-check
pnpm audit --audit-level=moderate
pnpm run deadcode:check
pnpm run dup:check
pnpm run test:safeall