name: Dead Code Detection

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  deadcode:
    name: Detect Dead Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Knip (Dead Code Analysis)
        run: npm run deadcode:ci

      - name: Generate readable report
        if: failure()
        run: npm run deadcode

      - name: Comment PR with results
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Dead code detected!** Run `npm run deadcode` locally to see details.'
            })
